export const CarListData = [
  {
    id: 1,
    name: "Sedan",
    seat: 4,
    desc: "Comfortable, spacious sedan for family trips",
    amount: 42,
    image: "/image/UberX_v1.png",
  },
  {
    id: 2,
    name: "SUV",
    seat: 5,
    desc: "Versatile SUV for adventures and road trips",
    amount: 45,
    image: "/image/UberComfort.png",
  },
  {
    id: 3,
    name: "Convertible",
    seat: 2,
    desc: "Fun and stylish convertible for a thrilling ride",
    amount: 48,
    image: "/image/UberX_Pet.png",
  },
  {
    id: 4,
    name: "Electric",
    seat: 4,
    desc: "Environment-friendly electric car for eco-conscious driving",
    amount: 50,
    image: "/image/UberXL_New.png",
  },
  {
    id: 5,
    name: "Luxury",
    seat: 5,
    desc: "Luxurious car with premium features and comfort",
    amount: 55,
    image: "/image/UberXL_New.png",
  },
];
